### ISSUE TITLE
Crash on Minecraft Init

### ISSUE THREAD

**Issue by RobKulesa** [mikroskeem/WorldEditCUI#10]
[crash-2019-09-23_16.37.50-client.txt](https://github.com/mikroskeem/WorldEditCUI/files/3644069/crash-2019-09-23_16.37.50-client.txt)

The controller that is called on line 71 of [FabricModWorldEditCUI.java](https://github.com/mikroskeem/WorldEditCUI/blob/master/src/main/java/eu/mikroskeem/worldeditcui/FabricModWorldEditCUI.java) is null and throws NullPointerException? Was onGameInitDone not called? Minecraft opens and shows the loading screen for a split second before crashing. 

No other mod loader is installed, java is updated (JDK 12.0.2), and mc still crashes with & without other mods in mod folder.

**Comment by delbertina** [comment]
AFAIK this is just an issue with the latest release. Was having the same issue and using the previous release works fine. Maybe see if that fixes your issue?

**Comment by RobKulesa** [comment]
Yup this actually fixed it. Thanks

**Comment by mikroskeem** [comment]
Can not reproduce with Fabric API 0.3.3+build.234 and Fabric 0.6.2+build.166

**Comment by mikroskeem** [comment]
Feel free to reopen the issue with proper reproduction steps and more information
