### ISSUE TITLE
1.15.1 update

### ISSUE THREAD

**Issue by mikroskeem** [mikroskeem/WorldEditCUI#11]
Changes what I haven't figured out yet:
- [ ] GameRenderer#renderCenter is gone
- [ ] MinecraftClient#init is gone
- [ ] GuiLighting class is gone

**Comment by enveeed** [comment]
May be worth looking into where Minecraft renders chunk boundaries in 1.15 (F3 + G) as those have a similar appearance as WorldEdit CUI lines

**Comment by enveeed** [comment]
Got it working on 1.15, still needs more testing and optimization tho. See enveeed/WorldEditCUI@fe8aa8766743664256689301541a7a1579e35606

<details>
<summary>Screenshots</summary>

![screenshot](https://s.put.re/GQVwf7zV.59.png)
![screenshot](https://s.put.re/Lwon1YnJ.14.png)
![screenshot](https://s.put.re/sHJ5cfY5.45.png)
![screenshot](https://s.put.re/a62hS3Y4.56.png)

</details>

**Comment by mikroskeem** [comment]
Amazing job, I'll look into your changes this or next week.

**Comment by enveeed** [comment]
Sounds good, I will test and optimize some stuff here and there and do a PR :)

**Comment by mikroskeem** [comment]
Feel free to open a draft PR

**Comment by mikroskeem** [comment]
This issue is no longer relevant because I merged enveeed's changes in myself.
