### ISSUE TITLE
Hidden Lines Rendering

### ISSUE THREAD

**Issue by svelez** [mikroskeem/WorldEditCUI#18]
To my eyes, rendering of hidden lines is different, but so subtle as to make it difficult to distinguish between those lines that should be visible and which are occluded, which in turn makes it hard to understand exactly what a selection includes.

I spent a brief amount of time trying to validate that the alpha blending is working well, or if I just needed to make the hidden lines more transparent, but didn't really come to any conclusions.

My question is, would it be appreciated if I made some effort to enhance the available options for line rendering... such as perhaps, not showing hidden grid lines, attenuating various lines with depth (i.e fog), or using other line styles (dashed/dotted etc).

Thanks

**Comment by mikroskeem** [comment]
I'm happy to merge in any improvements to rendering, I'm not skilled at all in OpenGL stuff 😄

**Comment by svelez** [comment]
👍 I just got latest, and it looks like #16 has helped things a lot.  I may still work on adding additional options, but am going to close this and open PRs when anything may be ready.
