### ISSUE TITLE
Selection doesn't appear when using Fabulous! graphic settings

### ISSUE THREAD

**Issue by Toseflo** [mikroskeem/WorldEditCUI#26]
When you select Faboulous! graphic settings, WorldEditCUI stops working.
Tested in version 1.16.1. I only had ModMenu and FabricAPI installed.

**Comment by mikroskeem** [comment]
Should be fixed in #23, will release new jar shortly.

**Comment by mikroskeem** [comment]
[1.16.1+02](https://github.com/mikroskeem/WorldEditCUI/releases/tag/1.16.1%2B02)

**Comment by Toseflo** [comment]
That was fast, thanks!
And I just figured out that I have to clear the filter to see all issues, because #23 wasn't showing up for me (I'm new to Github xD)
