### ISSUE TITLE
Changing hotkeys doesn't work without restart

### ISSUE THREAD

**Issue by Phoenix616** [mikroskeem/WorldEditCUI#28]
When trying to change the hotkeys in the menu they aren't actually changed ingame to anything else. A restart is required for the keys to apply.

**Comment by zml2008** [comment]
Hm, I can't reproduce this locally -- any more details on which rev of the mod you're using or other bits of your environment?

I don't see what would cause the issue though, since hotkeys use Vanilla's keybinding system and UI.

**Comment by Phoenix616** [comment]
Happened with fabric 0.9.0-build.204-1.16.1, fabric api 0.16.2+build.835 (I see there is an update of that, gonna test it with that soon), worldedit_cui-1.16.1_b244, ModMenu 1.14.5+build.30. Also I mean the keybind changing in the mod settings menu of ModMenu (the one which shows the key codes), not the Vanilla menu. (couldn't find keybindings in there?)

**Comment by zml2008** [comment]
`b244` is not a version released by us -- there is a known bad fork going around that's run by an idiot, which might be where that version came from. Latest on our end is https://github.com/mikroskeem/WorldEditCUI/releases/tag/1.16.1%2B02

**Comment by Phoenix616** [comment]
Oooh, I think I got that from this [curseforge page](https://www.curseforge.com/minecraft/mc-mods/worldeditcui-fabric-edition). That might be it.

**Comment by Phoenix616** [comment]
Yeah, definitely had the wrong version. Works properly in this one. Thanks for clearing this up! Sorry for not providing the versions directly :S

**Comment by zml2008** [comment]
no worries, glad you got things sorted out!
