### ISSUE TITLE
Configuration menu

### ISSUE THREAD

**Issue by mikroskeem** [mikroskeem/WorldEditCUI#3]
(this issue is just here as a reminder for myself and anyone else who can code & stumbles upon)

Pre-Fabric versions have config menus, this does not. Currently people have to modify json configuration file by hand to get desired settings.

**Comment by PointyDev** [comment]
@mikroskeem [ModMenu](https://github.com/Prospector/ModMenu) provides methods for creating a config screen, perhaps use this as an optional dependency to allow easy config?

**Comment by mikroskeem** [comment]
I think I have defined it as an optional dependency already, but I haven't had time to implement it.

Honestly it's low priority for me. PR-s are welcome before I get my hands on it.


---- On Mon, 12 Aug 2019 19:36:53 +0000 notifications@github.com wrote ----



@mikroskeem ModMenu provides methods for creating a config screen, perhaps use this as an optional dependency to allow easy config?

**Comment by mikroskeem** [comment]
In e-mail, I saw ModMenu. Too bad that edits won't be sent via e-mails

**Comment by StartForKillerMC** [comment]
Currently im working on the gui with ModMenu

**Comment by StartForKillerMC** [comment]
Okay, i have the first version working :)

![WECUI](https://user-images.githubusercontent.com/21644562/80614318-9889e200-8a3e-11ea-8479-6304f51e5f54.png)

**Comment by mikroskeem** [comment]
Looks good, get I18n support working as well and it's good to go.

**Comment by StartForKillerMC** [comment]
Yeah, it's not finished in that way, but i will do it.

**Comment by StartForKillerMC** [comment]
For example, what elements need to be translatable?

**Comment by StartForKillerMC** [comment]
![image](https://user-images.githubusercontent.com/21644562/80639666-9fc2e700-8a62-11ea-9afa-def5bc1fcd69.png)

Done!

**Comment by mikroskeem** [comment]
Solved by merging #15
