### ISSUE TITLE
(Question) worldeditcui and shaders

### ISSUE THREAD

**Issue by arturek1666** [mikroskeem/WorldEditCUI#35]
I had noticed that when shaders are on I can't see the borders at all :(, is there a way to fix it?
![image](https://user-images.githubusercontent.com/1558228/104664866-381ffb00-56c8-11eb-9866-10465b01d738.png)

I don't want to fix it by removing the shaders, i am hopping for some kind of fix in the between :)

**Comment by zml2008** [comment]
OptiFine shaders compatibility is an ongoing issue. The next release, planned for this Friday when Minecraft 1.16.5 is released, adds some limited shader compatibility. You'll be able to see lines in many cases, but the line weight might be off, and lines do not yet draw correctly over sky and water shaders.

**Comment by arturek1666** [comment]
yeah I just notice another issue, sorry for a dublication

**Comment by arturek1666** [comment]
Duplicate of #6 , Closing :)
