### ISSUE TITLE
[1.15.2_03] Does not work with newer Fabric Loader/API

### ISSUE THREAD

**Issue by acaciachan** [mikroskeem/WorldEditCUI#37]
[hs_err_pid13208.log](https://github.com/mikroskeem/WorldEditCUI/files/5925659/hs_err_pid13208.log)

**Comment by mikroskeem** [comment]
Need more information, such as installed mods (including WorldEditCUI version).

Besides, you also leaked your Minecraft access token - please always review hs_err_pid*.log before uploading to prevent sensitive data leakage.

**Comment by acaciachan** [comment]
When I use Fabric 0.10.8 and Fabric API(0.23.1) it works all okay,but when I updata fabric to 0.11.1 with Fabric API 0.28.5, succeed in launching game but failed to loading world ,I try this twice as the same reasult.
I load many mods,when I found the hs-err-pid13208.log was create in .minecraft ,I look it up and found World Edit CUI was reminded in it and I try to launch without WECUI and succesfully loading in all my world.
I am first few times to write issues and not well at this ,if you need more informations, please ask me for more.
I wil upload all my mods but github dont allow me?(>10MB) this crashed happened in a new created verson without any settings(No "configs"folder or options.txt or more) 
[2021-02-04-1.log.gz](https://github.com/mikroskeem/WorldEditCUI/files/5925977/2021-02-04-1.log.gz)

{2021-02-04-1(and 3).log failed with CUI}
{latest succeed without CUI}

[latest.log](https://github.com/mikroskeem/WorldEditCUI/files/5925996/latest.log)

I have checked there no sensitive data(at least for me maybe?)

**Comment by acaciachan** [comment]
Oh i Forget to say "the fail to loading world" is that the game stuck when show"loading 100%" for long time ,i try at least 3 times

**Comment by acaciachan** [comment]
worldEditCUI verson 1.15.2_03

**Comment by mikroskeem** [comment]
In conclusion:
- Minecraft version: 1.15.2
- Java version: 15.0.2+7-27
- WorldEditCUI version: 1.15.2_03

Works with Fabric Loader 0.10.8 & Fabric API 0.23.1, but breaks with Fabric Loader 0.11.1 & Fabric API 0.28.5. Probably expected, as older WorldEditCUI versions weren't made with infinite forwards compatibility in mind.

Can you reproduce this in a clean environment with newer Fabric Loader & API? Install only Fabric API & WorldEditCUI (and perhaps WorldEdit).

**Comment by acaciachan** [comment]
Tried, Also failed only using WECUI, fabric api and WE.also failed in Java 8(Minecraft official game include 1.8.0.51), JDK 14, Java8(1.8.0.281 that I installed)

**Comment by acaciachan** [comment]
[Uploading 错误报告 - 1.15.2-Fabric 0.11.1-test.zip…]()

**Comment by mikroskeem** [comment]
Not sure if I want to look into this, as I'm not very motivated on providing support for old Minecraft versions.

PRs welcome. Until then, I'll close the issue.

For now, either stick to older loader/API, or update the game.
