### ISSUE TITLE
Version 1.16.5+02 on Curseforge / Modrinth

### ISSUE THREAD

**Issue by Toseflo** [mikroskeem/WorldEditCUI#38]
I noticed that the newest version 1.16.5+02 isn't available on the [Curseforge page](https://www.curseforge.com/minecraft/mc-mods/worldeditcui-fabric). Also there is a new mod-hosting site called [modrinth.com](https://modrinth.com/). Would be cool if WorldEditCUI could also be released there =)

**Comment by mikroskeem** [comment]
https://www.curseforge.com/minecraft/mc-mods/worldeditcui-fabric/files/3196964

Will consider modrinth one day. No promises.
