### ISSUE TITLE
 command that runs automatically

### ISSUE THREAD

**Issue by thedourn** [mikroskeem/WorldEditCUI#4]
Hey,
How to disable the command that runs automatically on worldeditcui?

>.... [18:21:40 INFO]: thedourn logged in with entity id 293 at ([Survie]-9.0, 78.0, -16.0)
>.... [18:21:40 INFO]: thedourn issued server command: /we cui
>.... [18:21:40 INFO]: thedourn lost connection: You used a command too fast! Please, join the server again and wait more before using any command.
>.... [18:21:40 INFO]: [-] thedourn has left this server.

**Comment by mikroskeem** [comment]
Fixed in https://github.com/mikroskeem/WorldEditCUI/commit/0f2cc0b261dfb38ac6750f9ddb6123d4b73feea5
