### ISSUE TITLE
Update for 1.17 snapshots

### ISSUE THREAD

**Issue by Greg-J** [mikroskeem/WorldEditCUI#40]
With Fabric and WorldEdit both working on the latest snapshot(s) it'd be great for WorldEdit CUI to be updated as well.

**Comment by zml2008** [comment]
updated #34, probably works

**Comment by Greg-J** [comment]
@zml2008, What are the chances of getting a build for 1.17?

**Comment by zml2008** [comment]
we don't generally publish non-release builds, but you are welcome to build that branch yourself.

**Comment by Greg-J** [comment]
I know nothing about Minecraft/Java/Fabric development.

Would a plea from an appreciate user be enough for you to post an experimental build for the 1.17 snapshots?

**Comment by zml2008** [comment]
mojang redid a bunch of rendering recently and between waiting a few weeks for those changes to settle and the rather large amount of time I expect updating to take I don't expect an update particularly soon.
