### ISSUE TITLE
The mods doesn't work on server

### ISSUE THREAD

**Issue by Mqtteo0** [mikroskeem/WorldEditCUI#43]
As the title says, the mod doesn't works on servers, i don't know why, yes the server has worldedit, but it is a public server.
[latest.log](https://github.com/mikroskeem/WorldEditCUI/files/6735261/latest.log)

**Comment by mikroskeem** [comment]
Try without OptiFine and report back.

**Comment by Mqtteo0** [comment]
still doesn't work

**Comment by mikroskeem** [comment]
1) How are you testing the mod? Could you set up a minimal server with 1.16.5 (e.g Paper) & latest compatible WorldEdit installed for testing?
2) Is this server running ViaVersion and/or it's on version older than 1.13.x?

**Comment by Mqtteo0** [comment]
I'm using the mod on a public server 1.12.2, so the server isn't mine

**Comment by mikroskeem** [comment]
That explains. Unfortunately this mod does not work on servers older than 1.13.x due to plugin message packet using a different identifier.

**Comment by Mqtteo0** [comment]
I see, thanks a lot.
