### ISSUE TITLE
Cannot build due to maven.terraformersmc.com returning HTTP 521

### ISSUE THREAD

**Issue by HayateLaTech** [mikroskeem/WorldEditCUI#44]
I downloaded the latest repo of the 1.17 branch and tried to build it using the gradlew.bat file.

Turns out I can't build the project because..

> Could not GET 'https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu/2.0.0-beta.7/modmenu-2.0.0-beta.7.pom'. Received status code 521 from server: Origin Down

That's basically saying that Cloudflare couldn't connect to the underlying server, so it's just down as of rn..

Is there anything I could do to fix this problem or do I have to wait for their servers to be online again?

**Comment by mikroskeem** [comment]
Simply wait until it becomes online again. Nothing for you, or even us to do here about given repository being down (besides building the specified modmenu version by yourself).

**Comment by HayateLaTech** [comment]
It's working again 😁 🎉
