### ISSUE TITLE
Why no 1.17.1 yet?

### ISSUE THREAD

**Issue by FireBlaster08** [mikroskeem/WorldEditCUI#48]
I have been trying to find a version of WE CUI for 1.17.1 for over 2 months now, i really rely on the mod and it feels very weird not having it. When will it be updated?

**Comment by AquUpd** [comment]
Just get it from artifacts
https://github.com/mikroskeem/WorldEditCUI/actions/runs/1209658116

**Comment by AquUpd** [comment]
1.17 works on 1.17.1

**Comment by mikroskeem** [comment]
Use Discord for questions and general help.

**Comment by Greg-J** [comment]
> Just get it from artifacts
> https://github.com/mikroskeem/WorldEditCUI/actions/runs/1209658116

How does one "get it" from that link? I can't find an executable/build download in there.

**Comment by AquUpd** [comment]
> 
> 
> > Just get it from artifacts
> > https://github.com/mikroskeem/WorldEditCUI/actions/runs/1209658116
> 
> How does one "get it" from that link? I can't find an executable/build download in there.

> 
> 
> Use Discord for questions and general help.
