### ISSUE TITLE
Keybinds are spammed when holding

### ISSUE THREAD

**Issue by pointydev** [mikroskeem/WorldEditCUI#5]
Heya,

Just noticed, if you hold a keybind (or simply tap it too slowly), you'll end up spamming the action it's meant to perform (toggle view, clear selection, etc.). Just thought I'd mention seeing as this may cause people to get kicked for too many commands being issued.

![](https://pointy.needs-to-s.top/85urgRW.png)

Thanks,
Elliott

**Comment by mikroskeem** [comment]
While I haven't mentioned this anywhere but support Discord yet, I am aware of this issue. I haven't figured out a way yet how to trigger keybinds once instead of repeatedly.

**Comment by mikroskeem** [comment]
Are you able to build WorldEditCUI yourself from git? If so, then does cbb8ed40e9581daf915781cab4b7fd6335841014 make it better?
