### ISSUE TITLE
Worldedit just stopped woring double slash command is invalid

### ISSUE THREAD

**Issue by Alatarius** [mikroskeem/WorldEditCUI#63]
### WorldEditCUI Version

WorldEditCUI-1.18.2+01

### Fabric Version

0.10.2 for 1.18.2

### Fabric API Version

0.48.0

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEditCUI compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.

### Bug Description

Whenever I enter the double slash command (//) I get (Unknown or incomplete command, see below for error at position 1: /<--[HERE]) as an error. 
![error_in_worldedit](https://user-images.githubusercontent.com/101660302/158431145-656bfa68-f17d-4c43-bcde-26071e283ade.png)

### Expected Behavior

When entering double slash commands expected to open worldedit commands

### Reproduction Steps

1. ...Open chat box
2. ...type in '//' without the apostrophes
3. ...error pops up without even entering command

**Comment by wizjany** [comment]
wrong place?
